config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  as :user do
    delete '/delete_an_image/' => 'users/registrations#delete_an_image', as: :delete_an_image
  end

  resources :posts do
    resources :comments
  end

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def update
    @post = Post.find(params[:post_id])
    # @comment = @post.comments.update(comment_params)

  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:id, :name, :comment)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.id %>:</strong>
          <%= comment.comment %>
        </p>
      </div>
    </div>
      <%= link_to 'edit', edit_post_comment_path(comment) , class:"button"%>

      <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button is-danger", data: { confirm: 'Are you sure?' } %>
  </article>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

  <div class="field">
    <div class="control">
      <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label: 'Your username please' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.input :comment, input_html: { class: 'textarea' }, placeholder: "add a comment", wrapper: false, label: false  %>
    </div>
  </div>
  <%= f.button :submit, 'Respond', class: "button is-primary" %>
  <% end %>